### ISSUE TITLE
ffmpeg-sys-next fails to build on windows 10

### ISSUE THREAD

**Issue by kkettinger** [gyroflow/gyroflow#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried the latest build?

- [X] I have tried the latest build

### Gyroflow version

21074a21

### What operating system are you using?

Windows 10 19044.1586

### What GPU are you using?

RTX 3060

### What happened?

When following the build instructions for windows, cargo build fails with the following error:
`error: failed to run custom build command for ffmpeg-sys-next v5.0.1`

When running the build command:
```
cargo:rustc-link-search=native=D:\Entwicklung\Repositories\kkettinger\gyroflow\ext\ffmpeg-5.0-windows-desktop-clang-gpl-lite\lib
cargo:rustc-link-lib=dylib=avutil
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', C:\Users\kk\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-next-5.0.1\build.rs:147:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Relevant log output

```shell
cargo:rustc-link-search=native=D:\Entwicklung\Repositories\kkettinger\gyroflow\ext\ffmpeg-5.0-windows-desktop-clang-gpl-lite\lib
cargo:rustc-link-lib=dylib=avutil
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', C:\Users\kk\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-next-5.0.1\build.rs:147:39
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\result.rs:1690
   3: enum$<core::result::Result<alloc::string::String,enum$<std::env::VarError, 1, 18446744073709551615, NotUnicode> > >::unwrap<alloc::string::String,enum$<std::env::VarError, 1, 18446744073709551615, NotUnicode> >
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\result.rs:1018
   4: build_script_build::output
             at C:\Users\kk\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-next-5.0.1\build.rs:147
   5: build_script_build::check_features
             at C:\Users\kk\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-next-5.0.1\build.rs:462
   6: build_script_build::main
             at C:\Users\kk\.cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-next-5.0.1\build.rs:764
   7: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kkettinger** [comment]
After setting the right LIBCLANG_PATH path in the __env.ps1 file, it works now.
