### ISSUE TITLE
[Bug]: AppImage crash/exit when entering 

### ISSUE THREAD

**Issue by nerdCopter** [gyroflow/gyroflow#66]
### Gyroflow version

v1.0.0-rc1

### What operating system are you using?

Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

### What GPU are you using?

n/a - Intel integrated HD

### What happened?

entering any value in the motion data's lowpass filter Hz field results in crash/exit.
![2022-02-04_13-23](https://user-images.githubusercontent.com/56646290/152590854-bcfe288f-0107-434e-b381-ffb255be3c5c.png)

### Relevant log output

```shell
$ ./Gyroflow-linux64.AppImage 
MDK 0.14.0 (git 378299c) - Multimedia Development Kit. Copyright (c) 2016-2022 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux x86_64; Clang13.0.1 GCC4.2.1; libc++13000; 15:11:36 Feb  1 2022
19:28:06 [INFO] Lens profiles directory: "/tmp/user/1000/.mount_GyroflgCB2ZZ/camera_presets"
19:28:06 [INFO] Loaded 1289 lens profiles in 23.787ms
19:28:07 [INFO] Latest version: v1.0.0-rc1, current version: v1.0.0-rc1
19:28:09 [DEBUG] (10) MDKPlayer: [in m_player->onEvent] "reader.buffering" ""
19:28:09 [DEBUG] (11) MDKPlayer: [in m_player->onEvent] "thread.video" ""
19:28:09 [DEBUG] (12) MDKPlayer: [in m_player->onEvent] "thread.audio" ""
19:28:09 [DEBUG] (12) MDKPlayer: [in m_player->onEvent] "decoder.audio" "FFmpeg"
19:28:09 [DEBUG] (12) MDKPlayer: [in m_player->onEvent] "reader.buffering" ""
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
19:28:09 [DEBUG] (11) MDKPlayer: [in m_player->onEvent] "decoder.video" "AVCodec.MMAL.mmal"
19:28:09 [DEBUG] (13) MDKPlayer: [in VideoTextureNodePriv::createTexture] QSGRendererInterface::OpenGL
19:28:09 [DEBUG] (13) MDKPlayer: [in MDKPlayer::sync] created texture QSGPlainTexture(0x7fc59dc70680) QSize(1030, 579)
get Context 0x7fc59d842580/0x7fc59c0057c0 has no local data for key 0x2, create 1(0x7fc59dd4d700)
get Context 0x7fc59d842580/0x7fc59c0057c0 has no local data for key 0x1, create 1(0x7fc59d62a0a0)
19:28:11 [DEBUG] (13) MDKPlayer: [in m_player->onEvent] "render.video" "1st_frame"
19:28:11 [INFO] surface size: 1280x719
19:28:11 [ERROR] OpenCL error: 

################################ OPENCL ERROR ############################### 

Error executing function: clGetDeviceIDs  

Status error code: CL_DEVICE_NOT_FOUND (-1)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clGetDeviceIDs.html#errors  

############################################################################# 

MESA-INTEL: warning: Haswell Vulkan support is incomplete
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BadAccess', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/gles/egl.rs:759:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
19:28:11 [ERROR] Failed to initialize wgpu Any { .. }
19:28:13 [DEBUG] (13) MDKPlayer: [in VideoTextureNodePriv::createTexture] QSGRendererInterface::OpenGL
19:28:13 [DEBUG] (13) MDKPlayer: [in MDKPlayer::sync] created texture QSGPlainTexture(0x7fc59e18cf90) QSize(1280, 719)
19:28:13 [ERROR] OpenCL error: 

################################ OPENCL ERROR ############################### 

Error executing function: clGetDeviceIDs  

Status error code: CL_DEVICE_NOT_FOUND (-1)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clGetDeviceIDs.html#errors  

############################################################################# 

MESA-INTEL: warning: Haswell Vulkan support is incomplete
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BadAccess', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/gles/egl.rs:759:14
19:28:13 [ERROR] Failed to initialize wgpu Any { .. }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NegativeFrequency', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/biquad-0.4.2/src/frequency.rs:139:37
fatal runtime error: failed to initiate panic, error 5
Aborted

```
```

**Comment by AdrianEddy** [comment]
Fixed in 8173d46cbb57fb768ac60cd43b7f620a25350521
